export const SEQUENCE_PERSONALIZATION_SYSTEM_PROMPT = `You are a B2B sales development representative personalizing a template email touch for a prospect.
Your goal is to adapt the provided email template using the buyer's conversation context (problems, needs, quotes) to make it highly relevant and personal, without altering the overall goal and structure of the template.

Rules:
1. ONLY use information explicitly present in the provided conversation context. Never invent details, timelines, or specifications.
2. If the conversation context is empty, sparse, or doesn't match the theme of the template, return the template completely unchanged.
3. Keep the changes subtle and natural (e.g., replace a generic reference to "your challenges" with a specific reference to the buyer's stated problem like "your database scale limitations").
4. Never make the email sound robotic, generic, or like it was generated by an AI. Write exactly as a human representative following up would.
5. You MUST ensure the email greeting is exactly: "Dear [Name] ji," (e.g., "Dear John ji,").
6. You MUST ensure the subject line is short and catchy (maximum 6 words).
7. The output must start directly with "Subject: " and then the body separated by a line containing "---", exactly matching the format:
Subject: [Personalized Subject]
---
[Personalized Body]
`;

export interface DripTemplate {
  position: number;
  subject: string;
  body: string;
}

export const DRIP_TEMPLATES: DripTemplate[] = [
  {
    position: 2,
    subject: "Resource for your team",
    body: `Dear [Name] ji,

I was thinking about our conversation at the exhibition regarding [Company] and wanted to share a quick resource.

We recently published a short guide detailing how companies solve similar challenges with [Needs/Problem Topic]. I thought you and the team might find it useful.

You can read it here: https://yourdomain.com/resources/guide

Would love to know if the approach matches what you're currently building.

Best,
[Sender]`,
  },
  {
    position: 3,
    subject: "Quick question on [Needs Topic]",
    body: `Dear [Name] ji,

Hope you're having a good week.

I'm following up on our discussion about [Needs/Problem Topic]. Many organizations we work with find that the biggest bottleneck in addressing this is resource constraints.

Is this something [Company] is looking to tackle in the next quarter, or is it on the back burner for now?

Best,
[Sender]`,
  },
  {
    position: 4,
    subject: "Reviewing [Company]'s requirements",
    body: `Dear [Name] ji,

I was reviewing my notes from our chat at the booth. You mentioned that [Problem] was a key focus area.

We have a free architecture/process assessment where we take a look at your current setup and provide 3 concrete recommendations for optimization. There's no commitment at all—just some free advice from our engineering team.

Are you open to a quick 15-minute call next week to see if this assessment would make sense for [Company]?

Best,
[Sender]`,
  },
  {
    position: 5,
    subject: "Process walkthrough invite",
    body: `Dear [Name] ji,

Just wanted to check in. I know you've been busy navigating [Problem] at [Company].

We are hosting a small, invitation-only webinar next Thursday showing a live walkthrough of how B2B teams automate this exact workflow to save time and reduce manual errors.

If you'd like to join or get the recording, let me know and I'll add you to the list.

Best,
[Sender]`,
  },
  {
    position: 6,
    subject: "Closing the loop",
    body: `Dear [Name] ji,

I've reached out a few times regarding [Needs/Problem Topic] and haven't heard back, so I assume this is no longer a priority for [Company] or the timing isn't right.

I'm going to mark our conversation as closed for now. If things change and you want to revisit this in the future, please feel free to reach out.

I wish you the best of luck with your goals this year.

Best,
[Sender]`,
  },
];
